name: manual workflow

on: 
  workflow_dispatch:
    inputs:
     name:
       description: "Name"
       type: string
       default: test
     age:
      description: "Age"
      type: number
      required: true

jobs:
  manual:
   runs-on: ubuntu-latest

   steps:
   - name: Greetings from ma
     run: echo "${{ inputs.name }}"

   - name: New Age
     run: echo ${{ inputs.age }}
  
   

