name: manual workflow

on: 
  workflow_dispatch:
    inputs:
     name:
       description: "Name"
       type: string
       default: test
     age:
      description: "Age"
      type: number
      required: true
     gender:
       description: "Gender"
       type: choice
       options:
        - Male
        - Female
     married:
      description: "Married?"
      type: boolean
      
jobs:
  manual:
   runs-on: ubuntu-latest

   steps:
   - name: Greetings from ma
     run: echo "${{ inputs.name }}"

   - name: New Age
     run: echo ${{ inputs.age }}

   - name: New Gender
     run: echo ${{ inputs.gender }}

   - name: New Married
     run: echo ${{ inputs.married }}
  
   

