name: Schedule workflow 

on:
 workflow_dispatch:
 schedule:
 - cron: '*/5 * * * *'

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
     - name: log time
       run: |
         current_date_time=$(date)
         echo "current date and time: ${current_date_time}"
    
  
